version: 2
updates:
- package-ecosystem: gitsubmodule
  directory: "/"
  schedule:
    interval: daily
  commit-message:
      prefix: "Plugins"
  rebase-strategy: "disabled"
  open-pull-requests-limit: 1