# https://rust-lang.github.io/rustfmt

tab_spaces = 2
max_width = 132

imports_granularity = "Item"

reorder_imports = true
reorder_impl_items = true

format_code_in_doc_comments = true
format_macro_matchers = true
format_strings = true
wrap_comments = true
normalize_comments = true
normalize_doc_attributes = true
doc_comment_code_block_width = 80

hex_literal_case = "Upper"
match_arm_leading_pipes = "Always"

unstable_features = true
