DOXYFILE = 'Doxyfile-mcss'
MAIN_PROJECT_URL = 'https://orca-repos.github.io/orca'
FAVICON = 'Doxyfile-favicon.png'

STYLESHEETS = [
  'https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,400i,600,600i%7CSource+Code+Pro:400,400i,600&subset=latin-ext',
  '../css/m-dark+documentation.compiled.css'
]

FINE_PRINT = """<p><a href="https://github.com/orca-repos/orca">Orca</a> documentation.<br />Generated by <a href="https://doxygen.org/">Doxygen {doxygen_version}</a> and <a href="https://mcss.mosra.cz/">m.css</a>.</p>"""
SEARCH_HELP = """<p class="m-noindent">Search for symbols, directories, files, pages and Orca APIs. You can omit any prefix from the symbol or file path; adding a <code>:</code> or <code>/</code> suffix lists all members of given symbol or directory.</p> <p class="m-noindent">Use <span class="m-label m-dim">&darr;</span> / <span class="m-label m-dim">&uarr;</span> to navigate through the list, <span class="m-label m-dim">Enter</span> to go. <span class="m-label m-dim">Tab</span> autocompletes common prefix, you can copy a link to the result using <span class="m-label m-dim">⌘</span> <span class="m-label m-dim">L</span> while <span class="m-label m-dim">⌘</span> <span class="m-label m-dim">M</span> produces a Markdown link.</p>"""
