// SPDX-License-Identifier: GPL-3.0-only WITH Qt-GPL-exception-1.0

#pragma once

#include "icon.hpp"
#include "utils_global.hpp"

namespace Utils {
namespace Icons {

ORCA_UTILS_EXPORT extern const Icon HOME;
ORCA_UTILS_EXPORT extern const Icon HOME_TOOLBAR;
ORCA_UTILS_EXPORT extern const Icon EDIT_CLEAR;
ORCA_UTILS_EXPORT extern const Icon EDIT_CLEAR_TOOLBAR;
ORCA_UTILS_EXPORT extern const Icon LOCKED_TOOLBAR;
ORCA_UTILS_EXPORT extern const Icon LOCKED;
ORCA_UTILS_EXPORT extern const Icon UNLOCKED_TOOLBAR;
ORCA_UTILS_EXPORT extern const Icon UNLOCKED;
ORCA_UTILS_EXPORT extern const Icon PINNED;
ORCA_UTILS_EXPORT extern const Icon NEXT;
ORCA_UTILS_EXPORT extern const Icon NEXT_TOOLBAR;
ORCA_UTILS_EXPORT extern const Icon PREV;
ORCA_UTILS_EXPORT extern const Icon PREV_TOOLBAR;
ORCA_UTILS_EXPORT extern const Icon PROJECT;
ORCA_UTILS_EXPORT extern const Icon ZOOM;
ORCA_UTILS_EXPORT extern const Icon ZOOM_TOOLBAR;
ORCA_UTILS_EXPORT extern const Icon ZOOMIN_TOOLBAR;
ORCA_UTILS_EXPORT extern const Icon ZOOMOUT_TOOLBAR;
ORCA_UTILS_EXPORT extern const Icon FITTOVIEW_TOOLBAR;
ORCA_UTILS_EXPORT extern const Icon OK;
ORCA_UTILS_EXPORT extern const Icon NOTLOADED;
ORCA_UTILS_EXPORT extern const Icon BROKEN;
ORCA_UTILS_EXPORT extern const Icon BOOKMARK;
ORCA_UTILS_EXPORT extern const Icon BOOKMARK_TOOLBAR;
ORCA_UTILS_EXPORT extern const Icon BOOKMARK_TEXTEDITOR;
ORCA_UTILS_EXPORT extern const Icon SNAPSHOT_TOOLBAR;
ORCA_UTILS_EXPORT extern const Icon NEWSEARCH_TOOLBAR;
ORCA_UTILS_EXPORT extern const Icon SETTINGS_TOOLBAR;
ORCA_UTILS_EXPORT extern const Icon NEWFILE;
ORCA_UTILS_EXPORT extern const Icon OPENFILE;
ORCA_UTILS_EXPORT extern const Icon OPENFILE_TOOLBAR;
ORCA_UTILS_EXPORT extern const Icon SAVEFILE;
ORCA_UTILS_EXPORT extern const Icon SAVEFILE_TOOLBAR;
ORCA_UTILS_EXPORT extern const Icon EXPORTFILE_TOOLBAR;
ORCA_UTILS_EXPORT extern const Icon MULTIEXPORTFILE_TOOLBAR;
ORCA_UTILS_EXPORT extern const Icon UNKNOWN_FILE;
ORCA_UTILS_EXPORT extern const Icon DIR;
ORCA_UTILS_EXPORT extern const Icon UNDO;
ORCA_UTILS_EXPORT extern const Icon UNDO_TOOLBAR;
ORCA_UTILS_EXPORT extern const Icon REDO;
ORCA_UTILS_EXPORT extern const Icon REDO_TOOLBAR;
ORCA_UTILS_EXPORT extern const Icon COPY;
ORCA_UTILS_EXPORT extern const Icon COPY_TOOLBAR;
ORCA_UTILS_EXPORT extern const Icon PASTE;
ORCA_UTILS_EXPORT extern const Icon PASTE_TOOLBAR;
ORCA_UTILS_EXPORT extern const Icon CUT;
ORCA_UTILS_EXPORT extern const Icon CUT_TOOLBAR;
ORCA_UTILS_EXPORT extern const Icon RESET;
ORCA_UTILS_EXPORT extern const Icon RESET_TOOLBAR;
ORCA_UTILS_EXPORT extern const Icon ARROW_UP;
ORCA_UTILS_EXPORT extern const Icon ARROW_UP_TOOLBAR;
ORCA_UTILS_EXPORT extern const Icon ARROW_DOWN;
ORCA_UTILS_EXPORT extern const Icon ARROW_DOWN_TOOLBAR;
ORCA_UTILS_EXPORT extern const Icon MINUS;
ORCA_UTILS_EXPORT extern const Icon PLUS_TOOLBAR;
ORCA_UTILS_EXPORT extern const Icon PLUS;
ORCA_UTILS_EXPORT extern const Icon MAGNIFIER;
ORCA_UTILS_EXPORT extern const Icon CLEAN;
ORCA_UTILS_EXPORT extern const Icon CLEAN_TOOLBAR;
ORCA_UTILS_EXPORT extern const Icon RELOAD;
ORCA_UTILS_EXPORT extern const Icon RELOAD_TOOLBAR;
ORCA_UTILS_EXPORT extern const Icon TOGGLE_LEFT_SIDEBAR;
ORCA_UTILS_EXPORT extern const Icon TOGGLE_LEFT_SIDEBAR_TOOLBAR;
ORCA_UTILS_EXPORT extern const Icon TOGGLE_RIGHT_SIDEBAR;
ORCA_UTILS_EXPORT extern const Icon TOGGLE_RIGHT_SIDEBAR_TOOLBAR;
ORCA_UTILS_EXPORT extern const Icon CLOSE_TOOLBAR;
ORCA_UTILS_EXPORT extern const Icon CLOSE_FOREGROUND;
ORCA_UTILS_EXPORT extern const Icon CLOSE_BACKGROUND;
ORCA_UTILS_EXPORT extern const Icon SPLIT_HORIZONTAL;
ORCA_UTILS_EXPORT extern const Icon SPLIT_HORIZONTAL_TOOLBAR;
ORCA_UTILS_EXPORT extern const Icon SPLIT_VERTICAL;
ORCA_UTILS_EXPORT extern const Icon SPLIT_VERTICAL_TOOLBAR;
ORCA_UTILS_EXPORT extern const Icon CLOSE_SPLIT_TOP;
ORCA_UTILS_EXPORT extern const Icon CLOSE_SPLIT_BOTTOM;
ORCA_UTILS_EXPORT extern const Icon CLOSE_SPLIT_LEFT;
ORCA_UTILS_EXPORT extern const Icon CLOSE_SPLIT_RIGHT;
ORCA_UTILS_EXPORT extern const Icon FILTER;
ORCA_UTILS_EXPORT extern const Icon LINK;
ORCA_UTILS_EXPORT extern const Icon LINK_TOOLBAR;
ORCA_UTILS_EXPORT extern const Icon SORT_ALPHABETICALLY_TOOLBAR;
ORCA_UTILS_EXPORT extern const Icon TOGGLE_PROGRESSDETAILS_TOOLBAR;
ORCA_UTILS_EXPORT extern const Icon ONLINE;
ORCA_UTILS_EXPORT extern const Icon ONLINE_TOOLBAR;
ORCA_UTILS_EXPORT extern const Icon DOWNLOAD;
ORCA_UTILS_EXPORT extern const Icon INFO;
ORCA_UTILS_EXPORT extern const Icon INFO_TOOLBAR;
ORCA_UTILS_EXPORT extern const Icon WARNING;
ORCA_UTILS_EXPORT extern const Icon WARNING_TOOLBAR;
ORCA_UTILS_EXPORT extern const Icon CRITICAL;
ORCA_UTILS_EXPORT extern const Icon CRITICAL_TOOLBAR;
ORCA_UTILS_EXPORT extern const Icon ERROR_TASKBAR;
ORCA_UTILS_EXPORT extern const Icon EXPAND_ALL_TOOLBAR;
ORCA_UTILS_EXPORT extern const Icon TOOLBAR_EXTENSION;
ORCA_UTILS_EXPORT extern const Icon RUN_SMALL;
ORCA_UTILS_EXPORT extern const Icon RUN_SMALL_TOOLBAR;
ORCA_UTILS_EXPORT extern const Icon STOP_SMALL;
ORCA_UTILS_EXPORT extern const Icon STOP_SMALL_TOOLBAR;
ORCA_UTILS_EXPORT extern const Icon INTERRUPT_SMALL;
ORCA_UTILS_EXPORT extern const Icon INTERRUPT_SMALL_TOOLBAR;
ORCA_UTILS_EXPORT extern const Icon BOUNDING_RECT;
ORCA_UTILS_EXPORT extern const Icon EYE_OPEN_TOOLBAR;
ORCA_UTILS_EXPORT extern const Icon EYE_CLOSED_TOOLBAR;
ORCA_UTILS_EXPORT extern const Icon REPLACE;
ORCA_UTILS_EXPORT extern const Icon EXPAND;
ORCA_UTILS_EXPORT extern const Icon EXPAND_TOOLBAR;
ORCA_UTILS_EXPORT extern const Icon COLLAPSE;
ORCA_UTILS_EXPORT extern const Icon COLLAPSE_TOOLBAR;
ORCA_UTILS_EXPORT extern const Icon PAN_TOOLBAR;
ORCA_UTILS_EXPORT extern const Icon EMPTY14;
ORCA_UTILS_EXPORT extern const Icon EMPTY16;
ORCA_UTILS_EXPORT extern const Icon OVERLAY_ADD;
ORCA_UTILS_EXPORT extern const Icon OVERLAY_WARNING;
ORCA_UTILS_EXPORT extern const Icon OVERLAY_ERROR;
ORCA_UTILS_EXPORT extern const Icon RUN_FILE;
ORCA_UTILS_EXPORT extern const Icon RUN_FILE_TOOLBAR;
ORCA_UTILS_EXPORT extern const Icon RUN_SELECTED;
ORCA_UTILS_EXPORT extern const Icon RUN_SELECTED_TOOLBAR;
ORCA_UTILS_EXPORT extern const Icon CODEMODEL_ERROR;
ORCA_UTILS_EXPORT extern const Icon CODEMODEL_WARNING;
ORCA_UTILS_EXPORT extern const Icon CODEMODEL_DISABLED_ERROR;
ORCA_UTILS_EXPORT extern const Icon CODEMODEL_DISABLED_WARNING;
ORCA_UTILS_EXPORT extern const Icon CODEMODEL_FIXIT;
ORCA_UTILS_EXPORT extern const Icon MACOS_TOUCHBAR_BOOKMARK;
ORCA_UTILS_EXPORT extern const Icon MACOS_TOUCHBAR_CLEAR;
} // namespace Icons

namespace CodeModelIcon {

enum Type {
  Class = 0,
  Struct,
  Enum,
  Enumerator,
  FuncPublic,
  FuncProtected,
  FuncPrivate,
  FuncPublicStatic,
  FuncProtectedStatic,
  FuncPrivateStatic,
  Namespace,
  VarPublic,
  VarProtected,
  VarPrivate,
  VarPublicStatic,
  VarProtectedStatic,
  VarPrivateStatic,
  Signal,
  SlotPublic,
  SlotProtected,
  SlotPrivate,
  Keyword,
  Macro,
  Property,
  Unknown
};

ORCA_UTILS_EXPORT auto iconForType(Type type) -> QIcon;

} // namespace CodeModel
} // namespace Utils
